// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Saga struct {
	SagaID        uuid.UUID       `db:"saga_id"`
	Name          string          `db:"name"`
	FormattedName string          `db:"formatted_name"`
	Payload       json.RawMessage `db:"payload"`
	CreatedAt     time.Time       `db:"created_at"`
}

type SagaExecution struct {
	SagaExecutionID uuid.UUID       `db:"saga_execution_id"`
	SagaID          uuid.UUID       `db:"saga_id"`
	Payload         json.RawMessage `db:"payload"`
	CreatedAt       time.Time       `db:"created_at"`
}

type SagaStep struct {
	StepID uuid.UUID `db:"step_id"`
	SagaID uuid.UUID `db:"saga_id"`
	Index  int32     `db:"index"`
	Name   string    `db:"name"`
}

type StepExecution struct {
	StepExecutionID uuid.UUID `db:"step_execution_id"`
	SagaExecutionID uuid.UUID `db:"saga_execution_id"`
	Index           int32     `db:"index"`
	Name            string    `db:"name"`
	Status          string    `db:"status"`
}
